/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisitProofsRouteImport } from './routes/_authenticated/visit-proofs'
import { Route as AuthenticatedTreasuryRouteImport } from './routes/_authenticated/treasury'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProjectStatsRouteImport } from './routes/_authenticated/project-stats'
import { Route as AuthenticatedMyIncentivesRouteImport } from './routes/_authenticated/my-incentives'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedInstallmentsRouteImport } from './routes/_authenticated/installments'
import { Route as AuthenticatedIncentivesRouteImport } from './routes/_authenticated/incentives'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCancellationsRouteImport } from './routes/_authenticated/cancellations'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedTreasuryTransferIdRouteImport } from './routes/_authenticated/treasury_.$transferId'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects_.$id'
import { Route as AuthenticatedPlotsPlotIdBookRouteImport } from './routes/_authenticated/plots.$plotId.book'
import { Route as AuthenticatedPlotsPlotIdBookCheckoutRouteImport } from './routes/_authenticated/plots.$plotId.book.checkout'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitProofsRoute =
  AuthenticatedVisitProofsRouteImport.update({
    id: '/visit-proofs',
    path: '/visit-proofs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreasuryRoute = AuthenticatedTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectStatsRoute =
  AuthenticatedProjectStatsRouteImport.update({
    id: '/project-stats',
    path: '/project-stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyIncentivesRoute =
  AuthenticatedMyIncentivesRouteImport.update({
    id: '/my-incentives',
    path: '/my-incentives',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstallmentsRoute =
  AuthenticatedInstallmentsRouteImport.update({
    id: '/installments',
    path: '/installments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncentivesRoute = AuthenticatedIncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCancellationsRoute =
  AuthenticatedCancellationsRouteImport.update({
    id: '/cancellations',
    path: '/cancellations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreasuryTransferIdRoute =
  AuthenticatedTreasuryTransferIdRouteImport.update({
    id: '/treasury_/$transferId',
    path: '/treasury/$transferId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlotsPlotIdBookRoute =
  AuthenticatedPlotsPlotIdBookRouteImport.update({
    id: '/plots/$plotId/book',
    path: '/plots/$plotId/book',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlotsPlotIdBookCheckoutRoute =
  AuthenticatedPlotsPlotIdBookCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AuthenticatedPlotsPlotIdBookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/cancellations': typeof AuthenticatedCancellationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/incentives': typeof AuthenticatedIncentivesRoute
  '/installments': typeof AuthenticatedInstallmentsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-incentives': typeof AuthenticatedMyIncentivesRoute
  '/project-stats': typeof AuthenticatedProjectStatsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/treasury': typeof AuthenticatedTreasuryRoute
  '/visit-proofs': typeof AuthenticatedVisitProofsRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/treasury/$transferId': typeof AuthenticatedTreasuryTransferIdRoute
  '/plots/$plotId/book': typeof AuthenticatedPlotsPlotIdBookRouteWithChildren
  '/plots/$plotId/book/checkout': typeof AuthenticatedPlotsPlotIdBookCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/cancellations': typeof AuthenticatedCancellationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/incentives': typeof AuthenticatedIncentivesRoute
  '/installments': typeof AuthenticatedInstallmentsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-incentives': typeof AuthenticatedMyIncentivesRoute
  '/project-stats': typeof AuthenticatedProjectStatsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/treasury': typeof AuthenticatedTreasuryRoute
  '/visit-proofs': typeof AuthenticatedVisitProofsRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/treasury/$transferId': typeof AuthenticatedTreasuryTransferIdRoute
  '/plots/$plotId/book': typeof AuthenticatedPlotsPlotIdBookRouteWithChildren
  '/plots/$plotId/book/checkout': typeof AuthenticatedPlotsPlotIdBookCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/cancellations': typeof AuthenticatedCancellationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/incentives': typeof AuthenticatedIncentivesRoute
  '/_authenticated/installments': typeof AuthenticatedInstallmentsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-incentives': typeof AuthenticatedMyIncentivesRoute
  '/_authenticated/project-stats': typeof AuthenticatedProjectStatsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/treasury': typeof AuthenticatedTreasuryRoute
  '/_authenticated/visit-proofs': typeof AuthenticatedVisitProofsRoute
  '/_authenticated/projects_/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/treasury_/$transferId': typeof AuthenticatedTreasuryTransferIdRoute
  '/_authenticated/plots/$plotId/book': typeof AuthenticatedPlotsPlotIdBookRouteWithChildren
  '/_authenticated/plots/$plotId/book/checkout': typeof AuthenticatedPlotsPlotIdBookCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/approvals'
    | '/bookings'
    | '/cancellations'
    | '/dashboard'
    | '/documents'
    | '/incentives'
    | '/installments'
    | '/leads'
    | '/messages'
    | '/my-incentives'
    | '/project-stats'
    | '/projects'
    | '/team'
    | '/treasury'
    | '/visit-proofs'
    | '/projects/$id'
    | '/treasury/$transferId'
    | '/plots/$plotId/book'
    | '/plots/$plotId/book/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/approvals'
    | '/bookings'
    | '/cancellations'
    | '/dashboard'
    | '/documents'
    | '/incentives'
    | '/installments'
    | '/leads'
    | '/messages'
    | '/my-incentives'
    | '/project-stats'
    | '/projects'
    | '/team'
    | '/treasury'
    | '/visit-proofs'
    | '/projects/$id'
    | '/treasury/$transferId'
    | '/plots/$plotId/book'
    | '/plots/$plotId/book/checkout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/approvals'
    | '/_authenticated/bookings'
    | '/_authenticated/cancellations'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/incentives'
    | '/_authenticated/installments'
    | '/_authenticated/leads'
    | '/_authenticated/messages'
    | '/_authenticated/my-incentives'
    | '/_authenticated/project-stats'
    | '/_authenticated/projects'
    | '/_authenticated/team'
    | '/_authenticated/treasury'
    | '/_authenticated/visit-proofs'
    | '/_authenticated/projects_/$id'
    | '/_authenticated/treasury_/$transferId'
    | '/_authenticated/plots/$plotId/book'
    | '/_authenticated/plots/$plotId/book/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visit-proofs': {
      id: '/_authenticated/visit-proofs'
      path: '/visit-proofs'
      fullPath: '/visit-proofs'
      preLoaderRoute: typeof AuthenticatedVisitProofsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treasury': {
      id: '/_authenticated/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof AuthenticatedTreasuryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-stats': {
      id: '/_authenticated/project-stats'
      path: '/project-stats'
      fullPath: '/project-stats'
      preLoaderRoute: typeof AuthenticatedProjectStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-incentives': {
      id: '/_authenticated/my-incentives'
      path: '/my-incentives'
      fullPath: '/my-incentives'
      preLoaderRoute: typeof AuthenticatedMyIncentivesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/installments': {
      id: '/_authenticated/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof AuthenticatedInstallmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incentives': {
      id: '/_authenticated/incentives'
      path: '/incentives'
      fullPath: '/incentives'
      preLoaderRoute: typeof AuthenticatedIncentivesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cancellations': {
      id: '/_authenticated/cancellations'
      path: '/cancellations'
      fullPath: '/cancellations'
      preLoaderRoute: typeof AuthenticatedCancellationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treasury_/$transferId': {
      id: '/_authenticated/treasury_/$transferId'
      path: '/treasury/$transferId'
      fullPath: '/treasury/$transferId'
      preLoaderRoute: typeof AuthenticatedTreasuryTransferIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects_/$id': {
      id: '/_authenticated/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plots/$plotId/book': {
      id: '/_authenticated/plots/$plotId/book'
      path: '/plots/$plotId/book'
      fullPath: '/plots/$plotId/book'
      preLoaderRoute: typeof AuthenticatedPlotsPlotIdBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plots/$plotId/book/checkout': {
      id: '/_authenticated/plots/$plotId/book/checkout'
      path: '/checkout'
      fullPath: '/plots/$plotId/book/checkout'
      preLoaderRoute: typeof AuthenticatedPlotsPlotIdBookCheckoutRouteImport
      parentRoute: typeof AuthenticatedPlotsPlotIdBookRoute
    }
  }
}

interface AuthenticatedPlotsPlotIdBookRouteChildren {
  AuthenticatedPlotsPlotIdBookCheckoutRoute: typeof AuthenticatedPlotsPlotIdBookCheckoutRoute
}

const AuthenticatedPlotsPlotIdBookRouteChildren: AuthenticatedPlotsPlotIdBookRouteChildren =
  {
    AuthenticatedPlotsPlotIdBookCheckoutRoute:
      AuthenticatedPlotsPlotIdBookCheckoutRoute,
  }

const AuthenticatedPlotsPlotIdBookRouteWithChildren =
  AuthenticatedPlotsPlotIdBookRoute._addFileChildren(
    AuthenticatedPlotsPlotIdBookRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedCancellationsRoute: typeof AuthenticatedCancellationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedIncentivesRoute: typeof AuthenticatedIncentivesRoute
  AuthenticatedInstallmentsRoute: typeof AuthenticatedInstallmentsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyIncentivesRoute: typeof AuthenticatedMyIncentivesRoute
  AuthenticatedProjectStatsRoute: typeof AuthenticatedProjectStatsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTreasuryRoute: typeof AuthenticatedTreasuryRoute
  AuthenticatedVisitProofsRoute: typeof AuthenticatedVisitProofsRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedTreasuryTransferIdRoute: typeof AuthenticatedTreasuryTransferIdRoute
  AuthenticatedPlotsPlotIdBookRoute: typeof AuthenticatedPlotsPlotIdBookRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedCancellationsRoute: AuthenticatedCancellationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedIncentivesRoute: AuthenticatedIncentivesRoute,
  AuthenticatedInstallmentsRoute: AuthenticatedInstallmentsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyIncentivesRoute: AuthenticatedMyIncentivesRoute,
  AuthenticatedProjectStatsRoute: AuthenticatedProjectStatsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTreasuryRoute: AuthenticatedTreasuryRoute,
  AuthenticatedVisitProofsRoute: AuthenticatedVisitProofsRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedTreasuryTransferIdRoute: AuthenticatedTreasuryTransferIdRoute,
  AuthenticatedPlotsPlotIdBookRoute:
    AuthenticatedPlotsPlotIdBookRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
